---
cog_bundle_version: 3

name: github
version: 0.0.1
description: Interact with github
# docker:
#   image: cogcmd/github
#   tag: 0.0.1
permissions:
  - github:read
  - github:write
commands:
  pr:
    executable: /Users/vanstee/Code/cogcmd/github/cog-command
    # executable: /home/bundle/cog-command
    description: List stargazers for a repo
    documentation: |
      github:pr [list] [--open] [--closed] [--all] --repo=<repo> - List pull requests for a repo
    rules:
      - must have github:read
    options:
      repo:
        type: string
        required: true
      open:
        type: bool
        required: false
      closed:
        type: bool
        required: false
      all:
        type: bool
        required: false
  stargazer:
    executable: /Users/vanstee/Code/cogcmd/github/cog-command
    # executable: /home/bundle/cog-command
    description: List stargazers for a repo
    documentation: |
      github:stargazer --repo=<repo> - List stargazers for a repo
    rules:
      - must have github:read
    options:
      repo:
        type: string
        required: true
