---
cog_bundle_version: 3

name: github
version: 0.0.1
description: Interact with github
# docker:
#   image: cogcmd/github
#   tag: 0.0.1
permissions:
  - github:read
  - github:write
commands:
  stargazers:
    executable: /Users/vanstee/Code/cogcmd/github/cog-command
    # executable: /home/bundle/cog-command
    description: List stargazers for a repo
    documentation: |
      github:stargazers <repo> - List stargazers for a repo
    rules:
      - must have github:read
